set(SHARED_SRC_DIR ${CMAKE_CURRENT_LIST_DIR}/src)
set(SHARED_INC_DIR ${CMAKE_CURRENT_LIST_DIR}/inc)

set(SHARED_SRC ${SHARED_SRC}
)

set(SHARED_INC ${SHARED_INC}
${SHARED_INC_DIR}/shared_defines.hpp
)